<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #000000;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
    table tr td{ padding: 10px;}
    table tr{ font-size: 15px;}

    div#more-information
    {
        
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Listar Usuário</h1>
    <a href="/usuario/cadastrar">[CADASTRAR]</a> 
    <div id="more-information">
        <table>
            <tr>
                <td>ID</td>
                <td>Nome</td>
                <td>Login</td>
                <td>Senha</td>
                <td>Ação</td>
            </tr>
        <?php 
            if(is_array($this->usuario)){
                foreach ($this->usuario as $aValue){
                ?>
                <tr>
                    <td><?php echo $aValue['id'];?></td>
                    <td><?php echo $aValue['nome'];?></td>
                    <td><?php echo $aValue['login'];?></td>
                    <td><?php echo $aValue['senha'];?></td>
                    <td><a href="/usuario/editar/id/<?php echo $aValue['id'];?>">[EDITAR]</a> 
                    <a href="/usuario/excluir/id/<?php echo $aValue['id'];?>">[EXCLUIR]</a></td>
                </tr>            
                <?
                }
            }else{
                echo "<tr><td colspan='4'>Nenhum registro encontrado.</td></tr>";
            }
        ?>
            </table>
    </div>
</div>