<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #000000;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
    table tr td{ padding: 10px;}
    table tr{ font-size: 15px;}

    div#more-information
    {
        
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>EXCLUIR</h1>

    <h3><?php  #print_r($this->arrayTeste); ?></h3>

    <div id="more-information">
        
        
    <a href="/index">[VOLTAR]</a>
    </div>
</div>