<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php # echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
    <h1>Layout</h1> <?php $aUser = Zend_Auth::getInstance()->getIdentity(); if($aUser) { ?> Olá, <?php echo $aUser['nome']; ?> | <a href="/default/login/sair">SAIR</a> <?php } ?>
        <div style="border: 1px solid red; padding: 30px">
            <?php echo $this->layout()->content; ?>
            </div>
        </body>
</html>